name: Deploy
on:
  push:
    branches: deploy/deno
  pull_request:
    branches: deploy/deno

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "corepack enable pnpm && pnpm i"

      - name: Build step
        run: "pnpm build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "jiaoy"
          entrypoint: "https://deno.land/std@0.217.0/http/file_server.ts"
          root: "dist"
          
          
